# Generated by Django 5.2.8 on 2026-02-13 15:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "train_type",
                    models.CharField(
                        choices=[
                            ("EXP", "Express"),
                            ("SF", "Superfast"),
                            ("PASS", "Passenger"),
                            ("MEMU", "MEMU"),
                            ("EMU", "EMU"),
                            ("GDS", "Goods"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "bogie_type",
                    models.CharField(
                        choices=[
                            ("LHB", "LHB"),
                            ("ICF", "ICF"),
                            ("BOXN", "BOXN"),
                            ("BCN", "BCN"),
                            ("BOBRN", "BOBRN"),
                            ("BTPN", "BTPN"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("PASSENGER", "Passenger"),
                    ("STATION_MASTER", "Station Master"),
                    ("GOODS_MANAGER", "Goods Manager"),
                    ("TICKET_STAFF", "Ticket Counter Staff"),
                    ("STORE_STAFF", "Store Staff"),
                ],
                default="PASSENGER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.ImageField(blank=True, null=True, upload_to="profile/"),
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoreSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=100)),
                ("qty", models.PositiveIntegerField(default=1)),
                (
                    "unit_price_inr",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total_inr", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sold_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "cashier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="appname.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_date", models.DateField()),
                ("scheduled_time", models.TimeField()),
                ("sequence", models.PositiveIntegerField(default=0)),
                (
                    "direction",
                    models.CharField(
                        choices=[("UP", "Up"), ("DOWN", "Down")],
                        default="UP",
                        max_length=6,
                    ),
                ),
                (
                    "track_type",
                    models.CharField(
                        choices=[
                            ("MAIN", "Main"),
                            ("PLATFORM1", "Platform 1"),
                            ("PLATFORM2", "Platform 2"),
                            ("GOODS", "Goods"),
                        ],
                        default="MAIN",
                        max_length=12,
                    ),
                ),
                ("stops", models.BooleanField(default=True)),
                ("delay_minutes", models.PositiveIntegerField(default=0)),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="appname.train",
                    ),
                ),
            ],
            options={
                "ordering": ["service_date", "scheduled_time", "sequence"],
                "unique_together": {("train", "service_date")},
            },
        ),
        migrations.CreateModel(
            name="PassengerTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[("TRAIN", "Train"), ("PLATFORM", "Platform")],
                        default="TRAIN",
                        max_length=10,
                    ),
                ),
                (
                    "coach_class",
                    models.CharField(
                        choices=[
                            ("1A", "1A"),
                            ("2A", "2A"),
                            ("3A", "3A"),
                            ("SL", "SL"),
                            ("CC", "CC"),
                            ("2S", "2S"),
                            ("FC", "FC"),
                        ],
                        default="SL",
                        max_length=3,
                    ),
                ),
                ("pnr", models.CharField(max_length=10, unique=True)),
                ("amount_inr", models.DecimalField(decimal_places=2, max_digits=10)),
                ("booked_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="appname.trainschedule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoodsShipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight_kg", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "rate_per_kg_inr",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("amount_inr", models.DecimalField(decimal_places=2, max_digits=10)),
                ("label_no", models.CharField(max_length=20, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BOOKED", "Booked"),
                            ("IN_TRANSIT", "In Transit"),
                            ("DELIVERED", "Delivered"),
                        ],
                        default="BOOKED",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goods_shipments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="appname.trainschedule",
                    ),
                ),
            ],
        ),
    ]
