# Generated by Django 5.2.8 on 2026-02-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0002_train_user_role_alter_user_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="passengerticket",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("CANCELLED", "Cancelled")],
                default="ACTIVE",
                max_length=10,
            ),
        ),
    ]
