# Generated by Django 5.2.8 on 2026-02-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0005_product_user_assigned_store_storesale_product_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="trainschedule",
            unique_together={("train", "service_date", "direction", "scheduled_time")},
        ),
    ]
